security:
    enable_authenticator_manager: true

    # Password Hasher (Plain Text)
    password_hashers:
        App\Entity\Utilisateur: plaintext

    # User Provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: Email # Use the 'Email' field to load users

    # Firewalls
    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: app_login # Route to the login page
                check_path: app_login # Route where the login form is submitted
                enable_csrf: true # Enable CSRF protection
                default_target_path: app_utilisateur_index # Redirect to this route after successful login
            logout:
                path: app_logout # Route to log out
                target: app_login # Redirect to this route after logout
            lazy: true # Allow anonymous access

    # Access Control
    access_control:
        - { path: ^/, roles: PUBLIC_ACCESS } # Allow access to all routes for everyone