security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # Utilisation de Doctrine pour charger les utilisateurs depuis la base de données
        database_users:
            entity:
                class: App\Entity\Utilisateur  # Utilisateur entity
                property: Email                 # Use the 'Email' property for authentication

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: database_users  # Use the configured provider

            # Form login method (use 'Email' for login)
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout

    access_control:
        # Define access control rules
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/message/new, roles: ROLE_USER }  # Added access control for /message/new
