<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Chambre extends \App\Entity\Chambre implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'active' => [parent::class, 'active', null],
        "\0".parent::class."\0".'capacite' => [parent::class, 'capacite', null],
        "\0".parent::class."\0".'entretient' => [parent::class, 'entretient', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lits' => [parent::class, 'lits', null],
        "\0".parent::class."\0".'localisation' => [parent::class, 'localisation', null],
        "\0".parent::class."\0".'num' => [parent::class, 'num', null],
        "\0".parent::class."\0".'position' => [parent::class, 'position', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'active' => [parent::class, 'active', null],
        'capacite' => [parent::class, 'capacite', null],
        'entretient' => [parent::class, 'entretient', null],
        'id' => [parent::class, 'id', null],
        'lits' => [parent::class, 'lits', null],
        'localisation' => [parent::class, 'localisation', null],
        'num' => [parent::class, 'num', null],
        'position' => [parent::class, 'position', null],
        'type' => [parent::class, 'type', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
