<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Adress' => [parent::class, 'Adress', null],
        "\0".parent::class."\0".'Email' => [parent::class, 'Email', null],
        "\0".parent::class."\0".'Grade' => [parent::class, 'Grade', null],
        "\0".parent::class."\0".'Nom' => [parent::class, 'Nom', null],
        "\0".parent::class."\0".'Prenom' => [parent::class, 'Prenom', null],
        "\0".parent::class."\0".'Tel' => [parent::class, 'Tel', null],
        "\0".parent::class."\0".'entretientChambres' => [parent::class, 'entretientChambres', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'medecinSpecilaite' => [parent::class, 'medecinSpecilaite', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'resetToken' => [parent::class, 'resetToken', null],
        "\0".parent::class."\0".'resetTokenExpiresAt' => [parent::class, 'resetTokenExpiresAt', null],
        "\0".parent::class."\0".'service' => [parent::class, 'service', null],
        "\0".parent::class."\0".'utilisateurRole' => [parent::class, 'utilisateurRole', null],
        'Adress' => [parent::class, 'Adress', null],
        'Email' => [parent::class, 'Email', null],
        'Grade' => [parent::class, 'Grade', null],
        'Nom' => [parent::class, 'Nom', null],
        'Prenom' => [parent::class, 'Prenom', null],
        'Tel' => [parent::class, 'Tel', null],
        'entretientChambres' => [parent::class, 'entretientChambres', null],
        'id' => [parent::class, 'id', null],
        'medecinSpecilaite' => [parent::class, 'medecinSpecilaite', null],
        'password' => [parent::class, 'password', null],
        'resetToken' => [parent::class, 'resetToken', null],
        'resetTokenExpiresAt' => [parent::class, 'resetTokenExpiresAt', null],
        'service' => [parent::class, 'service', null],
        'utilisateurRole' => [parent::class, 'utilisateurRole', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
