<?php

namespace ContainerI0mDxdP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AdQao8sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.adQao8s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.adQao8s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chambreRepository' => ['privates', 'App\\Repository\\ChambreRepository', 'getChambreRepositoryService', true],
            'litRepository' => ['privates', 'App\\Repository\\LitRepository', 'getLitRepositoryService', true],
        ], [
            'chambreRepository' => 'App\\Repository\\ChambreRepository',
            'litRepository' => 'App\\Repository\\LitRepository',
        ]);
    }
}
