<?php

namespace ContainerI0mDxdP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BNiN74oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bNiN74o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bNiN74o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entretient' => ['privates', '.errored..service_locator.bNiN74o.App\\Entity\\EntretientChambre', NULL, 'Cannot autowire service ".service_locator.bNiN74o": it needs an instance of "App\\Entity\\EntretientChambre" but this type has been excluded in "config/services.yaml".'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'entretient' => 'App\\Entity\\EntretientChambre',
            'manager' => '?',
        ]);
    }
}
