<?php

namespace ContainerI0mDxdP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sfj7tV5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sfj7tV5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sfj7tV5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lit' => ['privates', '.errored..service_locator.sfj7tV5.App\\Entity\\Lit', NULL, 'Cannot autowire service ".service_locator.sfj7tV5": it needs an instance of "App\\Entity\\Lit" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lit' => 'App\\Entity\\Lit',
        ]);
    }
}
