<?php

namespace ContainerI0mDxdP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D4IYNcvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D4IYNcv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D4IYNcv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\LitRepository', 'getLitRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\LitRepository',
        ]);
    }
}
