<?php

namespace ContainerI0mDxdP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatbotHospitalierServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ChatbotHospitalierService' shared autowired service.
     *
     * @return \App\Service\ChatbotHospitalierService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ChatbotHospitalierService.php';

        return $container->privates['App\\Service\\ChatbotHospitalierService'] = new \App\Service\ChatbotHospitalierService(($container->privates['App\\Repository\\ChambreRepository'] ?? $container->load('getChambreRepositoryService')), ($container->privates['App\\Repository\\LitRepository'] ?? $container->load('getLitRepositoryService')), ($container->privates['App\\Repository\\EntretientChambreRepository'] ?? $container->load('getEntretientChambreRepositoryService')));
    }
}
