<?php

namespace ContainerI0mDxdP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChambre3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q0El6_K.App\Entity\Chambre' shared service.
     *
     * @return \App\Entity\Chambre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.q0El6_K": it needs an instance of "App\\Entity\\Chambre" but this type has been excluded in "config/services.yaml".');
    }
}
