<?php

namespace ContainerI0mDxdP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntretienServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EntretienService' shared autowired service.
     *
     * @return \App\Service\EntretienService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EntretienService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\EntretienService'])) {
            return $container->privates['App\\Service\\EntretienService'];
        }

        return $container->privates['App\\Service\\EntretienService'] = new \App\Service\EntretienService($a);
    }
}
