<?php

namespace ContainerI0mDxdP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestChatbotCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestChatbotCommand' shared autowired service.
     *
     * @return \App\Command\TestChatbotCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'TestChatbotCommand.php';

        $container->privates['App\\Command\\TestChatbotCommand'] = $instance = new \App\Command\TestChatbotCommand(($container->privates['App\\Service\\ChatbotHospitalierService'] ?? $container->load('getChatbotHospitalierServiceService')));

        $instance->setName('app:chatbot:test');

        return $instance;
    }
}
