<?php

namespace ContainerI0mDxdP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateExpiredEntretiensCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\UpdateExpiredEntretiensCommand' shared autowired service.
     *
     * @return \App\Command\UpdateExpiredEntretiensCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'UpdateExpiredEntretiensCommand.php';

        $container->privates['App\\Command\\UpdateExpiredEntretiensCommand'] = $instance = new \App\Command\UpdateExpiredEntretiensCommand(($container->privates['App\\Repository\\EntretientChambreRepository'] ?? $container->load('getEntretientChambreRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:update-expired-entretiens');
        $instance->setDescription('Mettre à jour les entretiens expirés comme terminés');

        return $instance;
    }
}
