<?php

namespace ContainerRfKhfu1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JZRbdMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._JZRbdM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._JZRbdM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entretienService' => ['privates', 'App\\Service\\EntretienService', 'getEntretienServiceService', true],
            'lit' => ['privates', '.errored..service_locator._JZRbdM.App\\Entity\\Lit', NULL, 'Cannot autowire service ".service_locator._JZRbdM": it needs an instance of "App\\Entity\\Lit" but this type has been excluded in "config/services.yaml".'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'entretienService' => 'App\\Service\\EntretienService',
            'lit' => 'App\\Entity\\Lit',
            'manager' => '?',
        ]);
    }
}
