<?php

namespace ContainerRfKhfu1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q0El6KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q0El6_K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q0El6_K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chambre' => ['privates', '.errored..service_locator.q0El6_K.App\\Entity\\Chambre', NULL, 'Cannot autowire service ".service_locator.q0El6_K": it needs an instance of "App\\Entity\\Chambre" but this type has been excluded in "config/services.yaml".'],
        ], [
            'chambre' => 'App\\Entity\\Chambre',
        ]);
    }
}
