<?php

namespace ContainerRfKhfu1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N9ieaknService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n9ieakn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n9ieakn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chambre' => ['privates', '.errored..service_locator.n9ieakn.App\\Entity\\Chambre', NULL, 'Cannot autowire service ".service_locator.n9ieakn": it needs an instance of "App\\Entity\\Chambre" but this type has been excluded in "config/services.yaml".'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repository' => ['privates', 'App\\Repository\\ChambreRepository', 'getChambreRepositoryService', true],
        ], [
            'chambre' => 'App\\Entity\\Chambre',
            'manager' => '?',
            'repository' => 'App\\Repository\\ChambreRepository',
        ]);
    }
}
