<?php

namespace ContainerRfKhfu1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntretientChambreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bNiN74o.App\Entity\EntretientChambre' shared service.
     *
     * @return \App\Entity\EntretientChambre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bNiN74o": it needs an instance of "App\\Entity\\EntretientChambre" but this type has been excluded in "config/services.yaml".');
    }
}
