<?php

namespace ContainerRfKhfu1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLit3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.b2aobrW.App\Entity\Lit' shared service.
     *
     * @return \App\Entity\Lit
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.b2aobrW": it needs an instance of "App\\Entity\\Lit" but this type has been excluded in "config/services.yaml".');
    }
}
