<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSDxqDWT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSDxqDWT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSDxqDWT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSDxqDWT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSDxqDWT\App_KernelDevDebugContainer([
    'container.build_hash' => 'SDxqDWT',
    'container.build_id' => 'f00867da',
    'container.build_time' => 1738361203,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSDxqDWT');
