<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRfKhfu1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRfKhfu1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRfKhfu1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRfKhfu1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRfKhfu1\App_KernelDevDebugContainer([
    'container.build_hash' => 'RfKhfu1',
    'container.build_id' => 'c310fbcb',
    'container.build_time' => 1741145807,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRfKhfu1');
